= GIOSimulator

*Creating GPIO projects in Java on the Raspberry Pi has never been this easy!*

== What is the GPIOSimulator

This project contains component classes for using sensors and actuators in java with the Rapsberry Pi. Additionally it has a rich tutorial to support new developers to try java for their GPIO projects raspberry pi project.

== Main Features

* Beginner friendly Component classes for easier usage of common sensors and actuators in Java

* Compatibility with the Grove Base Hat

* Compatiblity with Grove Sensors and Actuators

* A rich tutorial for explaining all components

* A sample project that shows how the components can work together


== Installation

Download the Jar from the releases: + 
https://github.com/FHNW-IP5-IP6/GPIOSimulator/releases/

Add the file to the ressources of your project and add a new gradle dependency.:

----
repositories {
    mavenCentral()
    flatDir {
        dirs 'build/libs'
    }
}

dependencies {
    implementation name: 'GPIOSimulator-0.1'
}
----

== Complete Tutorial

Visit the following page for a complete tutorial:

https://github.com/FHNW-IP5-IP6/GPIOSimulator/blob/dev/docs/Tutorial.adoc

You can generate an html file or any other file format from the `Tutorial.adoc` to make it as readable as possible.


